name = "speed-reader"
compatibility_date = "2024-05-01"
main = "worker.js"

[build]
command = "npm run build"
# The "watch_dir" is where wrangler will look for changes to trigger a rebuild.
# We watch the source files, not the dist or worker.js which are build artifacts.
watch_dir = ["./script.js", "./style.css", "./index.html", "./build.js"]

# For local development, you can temporarily add variables here.
# Example:
# [vars]
# DEEPSEEK_API_KEY = "your_key_here"
#
# !!! WARNING: DO NOT COMMIT THIS FILE WITH SECRETS IN IT !!!
# !!! It is recommended to solve the environment variable issue !!!
# !!! or add this file to .gitignore if you use it for local secrets. !!!
